// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 BoanLab @ DKU

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: event.proto

package protobuf

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IntentExporter_Stream_FullMethodName = "/kloudlens.v1.IntentExporter/Stream"
)

// IntentExporterClient is the client API for IntentExporter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// IntentExporter streams node-local IntentEvents to a collector. The
// agent initiates the stream; the collector replies with a single ack
// when the client closes its half.
type IntentExporterClient interface {
	Stream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[IntentEvent, StreamAck], error)
}

type intentExporterClient struct {
	cc grpc.ClientConnInterface
}

func NewIntentExporterClient(cc grpc.ClientConnInterface) IntentExporterClient {
	return &intentExporterClient{cc}
}

func (c *intentExporterClient) Stream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[IntentEvent, StreamAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &IntentExporter_ServiceDesc.Streams[0], IntentExporter_Stream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[IntentEvent, StreamAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type IntentExporter_StreamClient = grpc.ClientStreamingClient[IntentEvent, StreamAck]

// IntentExporterServer is the server API for IntentExporter service.
// All implementations must embed UnimplementedIntentExporterServer
// for forward compatibility.
//
// IntentExporter streams node-local IntentEvents to a collector. The
// agent initiates the stream; the collector replies with a single ack
// when the client closes its half.
type IntentExporterServer interface {
	Stream(grpc.ClientStreamingServer[IntentEvent, StreamAck]) error
	mustEmbedUnimplementedIntentExporterServer()
}

// UnimplementedIntentExporterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIntentExporterServer struct{}

func (UnimplementedIntentExporterServer) Stream(grpc.ClientStreamingServer[IntentEvent, StreamAck]) error {
	return status.Error(codes.Unimplemented, "method Stream not implemented")
}
func (UnimplementedIntentExporterServer) mustEmbedUnimplementedIntentExporterServer() {}
func (UnimplementedIntentExporterServer) testEmbeddedByValue()                        {}

// UnsafeIntentExporterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IntentExporterServer will
// result in compilation errors.
type UnsafeIntentExporterServer interface {
	mustEmbedUnimplementedIntentExporterServer()
}

func RegisterIntentExporterServer(s grpc.ServiceRegistrar, srv IntentExporterServer) {
	// If the following call panics, it indicates UnimplementedIntentExporterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IntentExporter_ServiceDesc, srv)
}

func _IntentExporter_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(IntentExporterServer).Stream(&grpc.GenericServerStream[IntentEvent, StreamAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type IntentExporter_StreamServer = grpc.ClientStreamingServer[IntentEvent, StreamAck]

// IntentExporter_ServiceDesc is the grpc.ServiceDesc for IntentExporter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IntentExporter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kloudlens.v1.IntentExporter",
	HandlerType: (*IntentExporterServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _IntentExporter_Stream_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "event.proto",
}

const (
	EventService_Subscribe_FullMethodName           = "/kloudlens.v1.EventService/Subscribe"
	EventService_Ack_FullMethodName                 = "/kloudlens.v1.EventService/Ack"
	EventService_Snapshot_FullMethodName            = "/kloudlens.v1.EventService/Snapshot"
	EventService_SubscribeIntents_FullMethodName    = "/kloudlens.v1.EventService/SubscribeIntents"
	EventService_SubscribeDeviations_FullMethodName = "/kloudlens.v1.EventService/SubscribeDeviations"
	EventService_SubscribeRaw_FullMethodName        = "/kloudlens.v1.EventService/SubscribeRaw"
	EventService_QueryGraph_FullMethodName          = "/kloudlens.v1.EventService/QueryGraph"
	EventService_SubscribeSession_FullMethodName    = "/kloudlens.v1.EventService/SubscribeSession"
)

// EventServiceClient is the client API for EventService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// EventService is the pull-side complement to IntentExporter — external
// subscribers connect to an agent (or aggregator) and pull events with a
// durable cursor.
type EventServiceClient interface {
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EventEnvelope], error)
	Ack(ctx context.Context, in *AckRequest, opts ...grpc.CallOption) (*AckResponse, error)
	Snapshot(ctx context.Context, in *SnapshotRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EventEnvelope], error)
	// Typed-stream RPCs. Subscribe() remains for consumers that want the
	// multiplexed EventEnvelope.
	//
	// SubscribeIntents is equivalent to Subscribe(streams=["intent"]) but the
	// response is IntentEvent directly (no envelope/cursor wrapping). Consumers
	// that already persist cursors out-of-band (prom/otel collectors) prefer
	// this shape — it halves wire size and removes the oneof unpacking cost.
	SubscribeIntents(ctx context.Context, in *IntentStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[IntentEvent], error)
	// SubscribeDeviations is the typed deviation tail — it stays live-only
	// because DeviationStreamRequest intentionally has no cursor field.
	// Clients that want cursor-based resume of past deviations should use the
	// generic Subscribe(streams=["deviation"]) envelope RPC, which replays
	// from the WAL's "deviation" stream via wal.AppendDeviation.
	SubscribeDeviations(ctx context.Context, in *DeviationStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DeviationEvent], error)
	// SubscribeRaw is the typed raw-syscall tail — live-only, no cursor,
	// gated by --enable-raw-stream on the agent because the event rate is
	// orders of magnitude higher than the intent stream. Clients that need
	// durable replay should use Subscribe(streams=["raw"]) which pulls
	// from the WAL's "raw" stream.
	SubscribeRaw(ctx context.Context, in *RawStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SyscallEvent], error)
	// QueryGraph runs a single fixed query against the agent's Session Graph
	// — lineage/peers/touches/reaches. Unary; large results are truncated by
	// max_depth rather than streamed.
	QueryGraph(ctx context.Context, in *GraphQuery, opts ...grpc.CallOption) (*GraphSnapshot, error)
	// SubscribeSession tails live edges scoped to one session. Emits a final
	// SessionUpdate{closed=true} when the session's TTL expires.
	SubscribeSession(ctx context.Context, in *SessionStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SessionUpdate], error)
}

type eventServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEventServiceClient(cc grpc.ClientConnInterface) EventServiceClient {
	return &eventServiceClient{cc}
}

func (c *eventServiceClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EventEnvelope], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EventService_ServiceDesc.Streams[0], EventService_Subscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, EventEnvelope]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EventService_SubscribeClient = grpc.ServerStreamingClient[EventEnvelope]

func (c *eventServiceClient) Ack(ctx context.Context, in *AckRequest, opts ...grpc.CallOption) (*AckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AckResponse)
	err := c.cc.Invoke(ctx, EventService_Ack_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) Snapshot(ctx context.Context, in *SnapshotRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EventEnvelope], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EventService_ServiceDesc.Streams[1], EventService_Snapshot_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SnapshotRequest, EventEnvelope]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EventService_SnapshotClient = grpc.ServerStreamingClient[EventEnvelope]

func (c *eventServiceClient) SubscribeIntents(ctx context.Context, in *IntentStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[IntentEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EventService_ServiceDesc.Streams[2], EventService_SubscribeIntents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[IntentStreamRequest, IntentEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EventService_SubscribeIntentsClient = grpc.ServerStreamingClient[IntentEvent]

func (c *eventServiceClient) SubscribeDeviations(ctx context.Context, in *DeviationStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DeviationEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EventService_ServiceDesc.Streams[3], EventService_SubscribeDeviations_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DeviationStreamRequest, DeviationEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EventService_SubscribeDeviationsClient = grpc.ServerStreamingClient[DeviationEvent]

func (c *eventServiceClient) SubscribeRaw(ctx context.Context, in *RawStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SyscallEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EventService_ServiceDesc.Streams[4], EventService_SubscribeRaw_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RawStreamRequest, SyscallEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EventService_SubscribeRawClient = grpc.ServerStreamingClient[SyscallEvent]

func (c *eventServiceClient) QueryGraph(ctx context.Context, in *GraphQuery, opts ...grpc.CallOption) (*GraphSnapshot, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GraphSnapshot)
	err := c.cc.Invoke(ctx, EventService_QueryGraph_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) SubscribeSession(ctx context.Context, in *SessionStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SessionUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EventService_ServiceDesc.Streams[5], EventService_SubscribeSession_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SessionStreamRequest, SessionUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EventService_SubscribeSessionClient = grpc.ServerStreamingClient[SessionUpdate]

// EventServiceServer is the server API for EventService service.
// All implementations must embed UnimplementedEventServiceServer
// for forward compatibility.
//
// EventService is the pull-side complement to IntentExporter — external
// subscribers connect to an agent (or aggregator) and pull events with a
// durable cursor.
type EventServiceServer interface {
	Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[EventEnvelope]) error
	Ack(context.Context, *AckRequest) (*AckResponse, error)
	Snapshot(*SnapshotRequest, grpc.ServerStreamingServer[EventEnvelope]) error
	// Typed-stream RPCs. Subscribe() remains for consumers that want the
	// multiplexed EventEnvelope.
	//
	// SubscribeIntents is equivalent to Subscribe(streams=["intent"]) but the
	// response is IntentEvent directly (no envelope/cursor wrapping). Consumers
	// that already persist cursors out-of-band (prom/otel collectors) prefer
	// this shape — it halves wire size and removes the oneof unpacking cost.
	SubscribeIntents(*IntentStreamRequest, grpc.ServerStreamingServer[IntentEvent]) error
	// SubscribeDeviations is the typed deviation tail — it stays live-only
	// because DeviationStreamRequest intentionally has no cursor field.
	// Clients that want cursor-based resume of past deviations should use the
	// generic Subscribe(streams=["deviation"]) envelope RPC, which replays
	// from the WAL's "deviation" stream via wal.AppendDeviation.
	SubscribeDeviations(*DeviationStreamRequest, grpc.ServerStreamingServer[DeviationEvent]) error
	// SubscribeRaw is the typed raw-syscall tail — live-only, no cursor,
	// gated by --enable-raw-stream on the agent because the event rate is
	// orders of magnitude higher than the intent stream. Clients that need
	// durable replay should use Subscribe(streams=["raw"]) which pulls
	// from the WAL's "raw" stream.
	SubscribeRaw(*RawStreamRequest, grpc.ServerStreamingServer[SyscallEvent]) error
	// QueryGraph runs a single fixed query against the agent's Session Graph
	// — lineage/peers/touches/reaches. Unary; large results are truncated by
	// max_depth rather than streamed.
	QueryGraph(context.Context, *GraphQuery) (*GraphSnapshot, error)
	// SubscribeSession tails live edges scoped to one session. Emits a final
	// SessionUpdate{closed=true} when the session's TTL expires.
	SubscribeSession(*SessionStreamRequest, grpc.ServerStreamingServer[SessionUpdate]) error
	mustEmbedUnimplementedEventServiceServer()
}

// UnimplementedEventServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEventServiceServer struct{}

func (UnimplementedEventServiceServer) Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[EventEnvelope]) error {
	return status.Error(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedEventServiceServer) Ack(context.Context, *AckRequest) (*AckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ack not implemented")
}
func (UnimplementedEventServiceServer) Snapshot(*SnapshotRequest, grpc.ServerStreamingServer[EventEnvelope]) error {
	return status.Error(codes.Unimplemented, "method Snapshot not implemented")
}
func (UnimplementedEventServiceServer) SubscribeIntents(*IntentStreamRequest, grpc.ServerStreamingServer[IntentEvent]) error {
	return status.Error(codes.Unimplemented, "method SubscribeIntents not implemented")
}
func (UnimplementedEventServiceServer) SubscribeDeviations(*DeviationStreamRequest, grpc.ServerStreamingServer[DeviationEvent]) error {
	return status.Error(codes.Unimplemented, "method SubscribeDeviations not implemented")
}
func (UnimplementedEventServiceServer) SubscribeRaw(*RawStreamRequest, grpc.ServerStreamingServer[SyscallEvent]) error {
	return status.Error(codes.Unimplemented, "method SubscribeRaw not implemented")
}
func (UnimplementedEventServiceServer) QueryGraph(context.Context, *GraphQuery) (*GraphSnapshot, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryGraph not implemented")
}
func (UnimplementedEventServiceServer) SubscribeSession(*SessionStreamRequest, grpc.ServerStreamingServer[SessionUpdate]) error {
	return status.Error(codes.Unimplemented, "method SubscribeSession not implemented")
}
func (UnimplementedEventServiceServer) mustEmbedUnimplementedEventServiceServer() {}
func (UnimplementedEventServiceServer) testEmbeddedByValue()                      {}

// UnsafeEventServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EventServiceServer will
// result in compilation errors.
type UnsafeEventServiceServer interface {
	mustEmbedUnimplementedEventServiceServer()
}

func RegisterEventServiceServer(s grpc.ServiceRegistrar, srv EventServiceServer) {
	// If the following call panics, it indicates UnimplementedEventServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EventService_ServiceDesc, srv)
}

func _EventService_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EventServiceServer).Subscribe(m, &grpc.GenericServerStream[SubscribeRequest, EventEnvelope]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EventService_SubscribeServer = grpc.ServerStreamingServer[EventEnvelope]

func _EventService_Ack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).Ack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_Ack_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).Ack(ctx, req.(*AckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_Snapshot_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SnapshotRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EventServiceServer).Snapshot(m, &grpc.GenericServerStream[SnapshotRequest, EventEnvelope]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EventService_SnapshotServer = grpc.ServerStreamingServer[EventEnvelope]

func _EventService_SubscribeIntents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(IntentStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EventServiceServer).SubscribeIntents(m, &grpc.GenericServerStream[IntentStreamRequest, IntentEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EventService_SubscribeIntentsServer = grpc.ServerStreamingServer[IntentEvent]

func _EventService_SubscribeDeviations_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DeviationStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EventServiceServer).SubscribeDeviations(m, &grpc.GenericServerStream[DeviationStreamRequest, DeviationEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EventService_SubscribeDeviationsServer = grpc.ServerStreamingServer[DeviationEvent]

func _EventService_SubscribeRaw_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RawStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EventServiceServer).SubscribeRaw(m, &grpc.GenericServerStream[RawStreamRequest, SyscallEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EventService_SubscribeRawServer = grpc.ServerStreamingServer[SyscallEvent]

func _EventService_QueryGraph_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GraphQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).QueryGraph(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_QueryGraph_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).QueryGraph(ctx, req.(*GraphQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_SubscribeSession_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SessionStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EventServiceServer).SubscribeSession(m, &grpc.GenericServerStream[SessionStreamRequest, SessionUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EventService_SubscribeSessionServer = grpc.ServerStreamingServer[SessionUpdate]

// EventService_ServiceDesc is the grpc.ServiceDesc for EventService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EventService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kloudlens.v1.EventService",
	HandlerType: (*EventServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ack",
			Handler:    _EventService_Ack_Handler,
		},
		{
			MethodName: "QueryGraph",
			Handler:    _EventService_QueryGraph_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _EventService_Subscribe_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Snapshot",
			Handler:       _EventService_Snapshot_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SubscribeIntents",
			Handler:       _EventService_SubscribeIntents_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SubscribeDeviations",
			Handler:       _EventService_SubscribeDeviations_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SubscribeRaw",
			Handler:       _EventService_SubscribeRaw_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SubscribeSession",
			Handler:       _EventService_SubscribeSession_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "event.proto",
}

const (
	AdminService_GetStatus_FullMethodName        = "/kloudlens.v1.AdminService/GetStatus"
	AdminService_ListPolicies_FullMethodName     = "/kloudlens.v1.AdminService/ListPolicies"
	AdminService_ApplyPolicy_FullMethodName      = "/kloudlens.v1.AdminService/ApplyPolicy"
	AdminService_DeletePolicy_FullMethodName     = "/kloudlens.v1.AdminService/DeletePolicy"
	AdminService_Diagnose_FullMethodName         = "/kloudlens.v1.AdminService/Diagnose"
	AdminService_GetCapabilities_FullMethodName  = "/kloudlens.v1.AdminService/GetCapabilities"
	AdminService_Top_FullMethodName              = "/kloudlens.v1.AdminService/Top"
	AdminService_Dump_FullMethodName             = "/kloudlens.v1.AdminService/Dump"
	AdminService_BaselineReset_FullMethodName    = "/kloudlens.v1.AdminService/BaselineReset"
	AdminService_BaselinePromote_FullMethodName  = "/kloudlens.v1.AdminService/BaselinePromote"
	AdminService_BaselineActivate_FullMethodName = "/kloudlens.v1.AdminService/BaselineActivate"
	AdminService_GetConfig_FullMethodName        = "/kloudlens.v1.AdminService/GetConfig"
	AdminService_SetConfig_FullMethodName        = "/kloudlens.v1.AdminService/SetConfig"
)

// AdminServiceClient is the client API for AdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AdminService is the klctl ↔ daemon control plane.
type AdminServiceClient interface {
	GetStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*AgentStatus, error)
	ListPolicies(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PolicyList, error)
	ApplyPolicy(ctx context.Context, in *Policy, opts ...grpc.CallOption) (*ApplyResult, error)
	DeletePolicy(ctx context.Context, in *PolicyRef, opts ...grpc.CallOption) (*DeleteResult, error)
	Diagnose(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*DiagnoseReport, error)
	GetCapabilities(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CapabilityReport, error)
	Top(ctx context.Context, in *TopRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TopSnapshot], error)
	Dump(ctx context.Context, in *DumpRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EventEnvelope], error)
	// Dynamic baseline lifecycle — lets klctl drive the learner/detector
	// without restarting kloudlens.
	BaselineReset(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	BaselinePromote(ctx context.Context, in *PromoteRequest, opts ...grpc.CallOption) (*PromoteResponse, error)
	BaselineActivate(ctx context.Context, in *ActivateRequest, opts ...grpc.CallOption) (*ActivateResponse, error)
	// Runtime-tunable configuration. GetConfig returns the whitelist of keys
	// the agent will accept via SetConfig; SetConfig applies one or more
	// key=value pairs atomically (per-key — there is no rollback across the
	// batch). Unknown keys come back in the errors map so klctl can print
	// them verbatim.
	GetConfig(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ConfigResponse, error)
	SetConfig(ctx context.Context, in *SetConfigRequest, opts ...grpc.CallOption) (*SetConfigResponse, error)
}

type adminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminServiceClient(cc grpc.ClientConnInterface) AdminServiceClient {
	return &adminServiceClient{cc}
}

func (c *adminServiceClient) GetStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*AgentStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentStatus)
	err := c.cc.Invoke(ctx, AdminService_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) ListPolicies(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PolicyList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PolicyList)
	err := c.cc.Invoke(ctx, AdminService_ListPolicies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) ApplyPolicy(ctx context.Context, in *Policy, opts ...grpc.CallOption) (*ApplyResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyResult)
	err := c.cc.Invoke(ctx, AdminService_ApplyPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) DeletePolicy(ctx context.Context, in *PolicyRef, opts ...grpc.CallOption) (*DeleteResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResult)
	err := c.cc.Invoke(ctx, AdminService_DeletePolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) Diagnose(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*DiagnoseReport, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DiagnoseReport)
	err := c.cc.Invoke(ctx, AdminService_Diagnose_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) GetCapabilities(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CapabilityReport, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CapabilityReport)
	err := c.cc.Invoke(ctx, AdminService_GetCapabilities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) Top(ctx context.Context, in *TopRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TopSnapshot], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AdminService_ServiceDesc.Streams[0], AdminService_Top_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TopRequest, TopSnapshot]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AdminService_TopClient = grpc.ServerStreamingClient[TopSnapshot]

func (c *adminServiceClient) Dump(ctx context.Context, in *DumpRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EventEnvelope], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AdminService_ServiceDesc.Streams[1], AdminService_Dump_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DumpRequest, EventEnvelope]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AdminService_DumpClient = grpc.ServerStreamingClient[EventEnvelope]

func (c *adminServiceClient) BaselineReset(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, AdminService_BaselineReset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) BaselinePromote(ctx context.Context, in *PromoteRequest, opts ...grpc.CallOption) (*PromoteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PromoteResponse)
	err := c.cc.Invoke(ctx, AdminService_BaselinePromote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) BaselineActivate(ctx context.Context, in *ActivateRequest, opts ...grpc.CallOption) (*ActivateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActivateResponse)
	err := c.cc.Invoke(ctx, AdminService_BaselineActivate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) GetConfig(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigResponse)
	err := c.cc.Invoke(ctx, AdminService_GetConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) SetConfig(ctx context.Context, in *SetConfigRequest, opts ...grpc.CallOption) (*SetConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetConfigResponse)
	err := c.cc.Invoke(ctx, AdminService_SetConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminServiceServer is the server API for AdminService service.
// All implementations must embed UnimplementedAdminServiceServer
// for forward compatibility.
//
// AdminService is the klctl ↔ daemon control plane.
type AdminServiceServer interface {
	GetStatus(context.Context, *Empty) (*AgentStatus, error)
	ListPolicies(context.Context, *Empty) (*PolicyList, error)
	ApplyPolicy(context.Context, *Policy) (*ApplyResult, error)
	DeletePolicy(context.Context, *PolicyRef) (*DeleteResult, error)
	Diagnose(context.Context, *Empty) (*DiagnoseReport, error)
	GetCapabilities(context.Context, *Empty) (*CapabilityReport, error)
	Top(*TopRequest, grpc.ServerStreamingServer[TopSnapshot]) error
	Dump(*DumpRequest, grpc.ServerStreamingServer[EventEnvelope]) error
	// Dynamic baseline lifecycle — lets klctl drive the learner/detector
	// without restarting kloudlens.
	BaselineReset(context.Context, *Empty) (*Empty, error)
	BaselinePromote(context.Context, *PromoteRequest) (*PromoteResponse, error)
	BaselineActivate(context.Context, *ActivateRequest) (*ActivateResponse, error)
	// Runtime-tunable configuration. GetConfig returns the whitelist of keys
	// the agent will accept via SetConfig; SetConfig applies one or more
	// key=value pairs atomically (per-key — there is no rollback across the
	// batch). Unknown keys come back in the errors map so klctl can print
	// them verbatim.
	GetConfig(context.Context, *Empty) (*ConfigResponse, error)
	SetConfig(context.Context, *SetConfigRequest) (*SetConfigResponse, error)
	mustEmbedUnimplementedAdminServiceServer()
}

// UnimplementedAdminServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdminServiceServer struct{}

func (UnimplementedAdminServiceServer) GetStatus(context.Context, *Empty) (*AgentStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedAdminServiceServer) ListPolicies(context.Context, *Empty) (*PolicyList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPolicies not implemented")
}
func (UnimplementedAdminServiceServer) ApplyPolicy(context.Context, *Policy) (*ApplyResult, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyPolicy not implemented")
}
func (UnimplementedAdminServiceServer) DeletePolicy(context.Context, *PolicyRef) (*DeleteResult, error) {
	return nil, status.Error(codes.Unimplemented, "method DeletePolicy not implemented")
}
func (UnimplementedAdminServiceServer) Diagnose(context.Context, *Empty) (*DiagnoseReport, error) {
	return nil, status.Error(codes.Unimplemented, "method Diagnose not implemented")
}
func (UnimplementedAdminServiceServer) GetCapabilities(context.Context, *Empty) (*CapabilityReport, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCapabilities not implemented")
}
func (UnimplementedAdminServiceServer) Top(*TopRequest, grpc.ServerStreamingServer[TopSnapshot]) error {
	return status.Error(codes.Unimplemented, "method Top not implemented")
}
func (UnimplementedAdminServiceServer) Dump(*DumpRequest, grpc.ServerStreamingServer[EventEnvelope]) error {
	return status.Error(codes.Unimplemented, "method Dump not implemented")
}
func (UnimplementedAdminServiceServer) BaselineReset(context.Context, *Empty) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method BaselineReset not implemented")
}
func (UnimplementedAdminServiceServer) BaselinePromote(context.Context, *PromoteRequest) (*PromoteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BaselinePromote not implemented")
}
func (UnimplementedAdminServiceServer) BaselineActivate(context.Context, *ActivateRequest) (*ActivateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BaselineActivate not implemented")
}
func (UnimplementedAdminServiceServer) GetConfig(context.Context, *Empty) (*ConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConfig not implemented")
}
func (UnimplementedAdminServiceServer) SetConfig(context.Context, *SetConfigRequest) (*SetConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetConfig not implemented")
}
func (UnimplementedAdminServiceServer) mustEmbedUnimplementedAdminServiceServer() {}
func (UnimplementedAdminServiceServer) testEmbeddedByValue()                      {}

// UnsafeAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminServiceServer will
// result in compilation errors.
type UnsafeAdminServiceServer interface {
	mustEmbedUnimplementedAdminServiceServer()
}

func RegisterAdminServiceServer(s grpc.ServiceRegistrar, srv AdminServiceServer) {
	// If the following call panics, it indicates UnimplementedAdminServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdminService_ServiceDesc, srv)
}

func _AdminService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetStatus(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_ListPolicies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).ListPolicies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_ListPolicies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).ListPolicies(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_ApplyPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Policy)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).ApplyPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_ApplyPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).ApplyPolicy(ctx, req.(*Policy))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_DeletePolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PolicyRef)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).DeletePolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_DeletePolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).DeletePolicy(ctx, req.(*PolicyRef))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_Diagnose_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).Diagnose(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_Diagnose_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).Diagnose(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_GetCapabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetCapabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_GetCapabilities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetCapabilities(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_Top_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TopRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AdminServiceServer).Top(m, &grpc.GenericServerStream[TopRequest, TopSnapshot]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AdminService_TopServer = grpc.ServerStreamingServer[TopSnapshot]

func _AdminService_Dump_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DumpRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AdminServiceServer).Dump(m, &grpc.GenericServerStream[DumpRequest, EventEnvelope]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AdminService_DumpServer = grpc.ServerStreamingServer[EventEnvelope]

func _AdminService_BaselineReset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).BaselineReset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_BaselineReset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).BaselineReset(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_BaselinePromote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PromoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).BaselinePromote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_BaselinePromote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).BaselinePromote(ctx, req.(*PromoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_BaselineActivate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).BaselineActivate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_BaselineActivate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).BaselineActivate(ctx, req.(*ActivateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_GetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_GetConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetConfig(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_SetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).SetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_SetConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).SetConfig(ctx, req.(*SetConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AdminService_ServiceDesc is the grpc.ServiceDesc for AdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kloudlens.v1.AdminService",
	HandlerType: (*AdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStatus",
			Handler:    _AdminService_GetStatus_Handler,
		},
		{
			MethodName: "ListPolicies",
			Handler:    _AdminService_ListPolicies_Handler,
		},
		{
			MethodName: "ApplyPolicy",
			Handler:    _AdminService_ApplyPolicy_Handler,
		},
		{
			MethodName: "DeletePolicy",
			Handler:    _AdminService_DeletePolicy_Handler,
		},
		{
			MethodName: "Diagnose",
			Handler:    _AdminService_Diagnose_Handler,
		},
		{
			MethodName: "GetCapabilities",
			Handler:    _AdminService_GetCapabilities_Handler,
		},
		{
			MethodName: "BaselineReset",
			Handler:    _AdminService_BaselineReset_Handler,
		},
		{
			MethodName: "BaselinePromote",
			Handler:    _AdminService_BaselinePromote_Handler,
		},
		{
			MethodName: "BaselineActivate",
			Handler:    _AdminService_BaselineActivate_Handler,
		},
		{
			MethodName: "GetConfig",
			Handler:    _AdminService_GetConfig_Handler,
		},
		{
			MethodName: "SetConfig",
			Handler:    _AdminService_SetConfig_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Top",
			Handler:       _AdminService_Top_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Dump",
			Handler:       _AdminService_Dump_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "event.proto",
}
